### PR TITLE
add CI pipeline

### PR DESCRIPTION
**Pull request by leo-schick**
This adds now a Github CI pipeline testing basic PostgreSQL commands against a postgres 14 db.

The nice thing is that we now have a docker-compose file behind our tests which makes it possible to add other CI tests e.g. copy from PostgreSQL to MySQL or SQL Server.

### CODE REVIEW

**Comment by leo-schick** [comment]
@jankatins any feedback to this?

The only thing I don't like in the current implementation is the fact that I don't know how to check if the postgres db is already running. I added a simple port check but that seems not to work, so I added a sleep timer for 7 seconds:

image

Maybe you have an idea how this could be improved.

**Comment by jankatins** [comment]
Improve (from experience with such things in a reconsiliation loop and doing integration tests with real cloud instances): loop which sleeps ~1s (short compares to timeout) and tries again and again until it reaches a timeout. Timeout should be 3-4x a reasonable time to not fail if running into outliers.

**Comment by leo-schick** [comment]
The question is how how to check if the service is available. The loop logic is already part of pytest-docker, see here: https://pypi.org/project/pytest-docker/

Would you suggest to do the connection test via SQLAlchemy?

**Comment by jankatins** [comment]
> Would you suggest to do the connection test via SQLAlchemy?

Yes: nothing is worse than flaky tests

**Comment by leo-schick** [comment]
@jankatins I fixed it now by using the [`pool_pre_ping`](https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine.params.pool_pre_ping) feature in SQLAlchemy.

In addition I did a bit of refactoring: I moved the generation of the sqlalchemy url into a property of the dbs.DB class. The method `mara_db.sqlalchemy_engine.engine` still works as expected. I added a basic test for SQLAlchemy as well to validate this.

**Pull request merged**
